### ISSUE TITLE
Heartbeats and external clock

### ISSUE THREAD

**Issue by jheusser** [paritytrading/philadelphia#34]
Having full control over the internal session clock is good though it seems to make complying with the FIX protocol with respect to heartbeats a bit difficult perhaps. On an idle session how frequently do you have to update the clock (calling `updateCurrentTimestamp`) and how frequently do you have to call `keepAlive` to make a heartbeat work without running into `TestRequest` from the acceptor?

Assuming 30s keepalive, I would have expected that calling every 1 second `updateCurrentTimestamp` and 30 second `keepAlive`  to work?

**Comment by jvirtanen** [comment]
The current timestamp (updated with `updateCurrentTimestamp`) is used for keep-alive as well as for all outgoing messages. The most important aspect regarding its update frequency is the clock accuracy required by the trading venue.

The keep-alive mechanism (run by `keepAlive`) does three things:

1. It checks whether at least HeartBtInt(108) has passed since sending the last message. If yes, it sends a Heartbeat message.

2. (If a Test Request message has not been sent.) It checks whether at least HeartBtInt(108) has passed since receiving the last message. If yes, it sends a Test Request message.

3. (If a Test Request message has been sent.) It checks whether at least HeartBtInt(108) + 10% has passed since receiving the last message. If yes, it invokes the heartbeat timeout callback.

If HeartBtInt(108) is 30 seconds and you invoke `keepAlive` every 30 seconds, you can end up in the following situation:

1. You send a message at time _T_.

2. You invoke `keepAlive` at time _T_ + 29 seconds. The keep-alive mechanism determines that less than HeartBtInt(108) has passed since sending the last message.

3. You get a Test Request message approximately at _T_ + 32 seconds.

Therefore, to avoid receiving Test Request messages, update frequency for the keep-alive mechanism should be less than 10% of HeartBtInt(108).

If you don't send messages other than Logon and Heartbeat and you invoke `keepAlive` at a frequency of (slightly over) 30 seconds starting from the Logon message, you should send Heartbeat messages always on time. However, if you are early with the invocation, a Heartbeat message will not be sent in time as the keep-alive mechanism determines that a duration less than or equal to HeartBt(108) has passed since sending the last message.

Does this help?

**Comment by jheusser** [comment]
Thanks a lot @jvirtanen for the clear answer, I was missing the 10% bit.
