### ISSUE TITLE
String representation of FIXMessage

### ISSUE THREAD

**Issue by Hema-Chandra** [paritytrading/philadelphia#41]
I have started working with philadelphia and it's pretty good till now. I wanted to know one thing. I have seen the examples and I am working with them know. I can able to send a message to acceptor from initiator and can receive the response in the "Initiator" class , " message(FIXMessage message) " method which is again declared in the interface "FIXMessageListener". I just wrote System.out.println(message.toString()). But I am getting the output as "com.paritytrading.philadelphia.FIXMessage@2328c243" . But I want the message like 
"8=FIX.4.2 | 9=120 | 49=sender | 52=timestamp | 56=target | .............. | 10=checksum "

1)  Is there any way to do so?
2)  I am a bit confused. where will I receive the response in the Initiator and the Acceptor class at first if we place an order?
3)  And another thing like : Is there any validation of the Incoming messages on the Acceptor and the Initiator side?
4)  As soon as I send an order from Initiator, it is getting stopped. How can I make this running continuously?

**Comment by jvirtanen** [comment]
1. There's currently no way to pretty-print a [`FIXMessage`](https://github.com/paritytrading/philadelphia/blob/master/libraries/core/src/main/java/com/paritytrading/philadelphia/FIXMessage.java) object. This is partly because the operation would have subtly worse performance profile than the other available operations. You can implement this by iterating over the fields in a message in the [`FIXMessageListener#message()`](https://github.com/paritytrading/philadelphia/blob/master/libraries/core/src/main/java/com/paritytrading/philadelphia/FIXMessageListener.java#L16) callback.
2. When you call [`FIXSession#receive()`](https://github.com/paritytrading/philadelphia/blob/master/libraries/core/src/main/java/com/paritytrading/philadelphia/FIXSession.java#L379), Philadelphia processes the received data and invokes the `FIXMessageListener#message()` callback whenever a message is parsed.
3. There is some validation, such as checking MsgSeqSum(34). This is implemented in the [`MessageHandler#receive()`](https://github.com/paritytrading/philadelphia/blob/master/libraries/core/src/main/java/com/paritytrading/philadelphia/FIXSession.java#L513) method.
4. In general, to keep the process running you need to keep receiving data by invoking the `FIXSession#receive()` method.

Other things to note:
- The `FIXMessageListener#message()` callback is always called with the same `FIXMessage` instance. When in the callback, grab the data you need, as it will be overwritten by the time the next message is parsed.
- A [`FIXSession`](https://github.com/paritytrading/philadelphia/blob/master/libraries/core/src/main/java/com/paritytrading/philadelphia/FIXSession.java) is in reality more like a FIX connection.
- [Parity FIX Gateway](https://github.com/paritytrading/parity/blob/master/applications/fix) is a more comprehensive example of a FIX acceptor implemented using Philadelphia.
- [GDAX FIX Example](https://github.com/jvirtanen/gdax-fix-example) is a more comprehensive example of a FIX initiator implemented using Philadelphia.

I hope this helps! Let me know if you have further questions.

**Comment by jvirtanen** [comment]
`FIXMessage#toString()` was implemented in #44.

**Comment by daybyter** [comment]
Is there a way to see the message that is actually sent? Including length, timestamp etc field? Or just use something like tcpdump to see the sent string?

**Comment by jvirtanen** [comment]
BeginString(8), BodyLength(9), and CheckSum(10) are handled outside `FIXMessage`. So, no, there's no simple way to do that from within an application. Something like tcpdump is your best bet.
